server:
  port: 6688
  db_url: postgres://postgres:123456@127.0.0.1:5432/chat
auth:
  ek: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEINt83pkz6QbbyKjJDGUOreYNe1ZT7ZQBFFe6vHeaGvv1
    -----END PRIVATE KEY-----
  dk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAN+Nslce6W3pWre+6gWuC9QyN6pAQNQSyjM7SiobR6V8=
    -----END PUBLIC KEY-----
