@base_url=http://localhost:6688

### signup
POST {{base_url}}/api/signup
Content-Type: application/json

{
  "workspace": "g1",
  "fullname": "wiki2",
  "email": "wiki2@gmail.com",
  "password": "123456"
}


### signin
# @name signin
POST {{base_url}}/api/signin
Content-Type: application/json

{
  "email": "charmfocus@gmail.com",
  "password": "123456"
}

@token = {{signin.response.body.token}}

### signin-err
POST {{base_url}}/api/signin-err
Content-Type: application/json

{
  "email": "charmfocus@gmail.com",
  "password": "1234567"
}


### get chat list
# @name chatlist
GET {{base_url}}/api/chat
Authorization: Bearer {{token}}

### get user list
GET {{base_url}}/api/users
Authorization: Bearer {{token}}
